# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b25d9940afcbecdf43ae9b86221ede3b9706002f910c2ac7ab9b7ae06d5a7f46d116ad6405581fecb125c20bec7787a78492c3ed66043bb56f1fe6972af7d234

test:
  secret_key_base: bf2ff1f78a157af926e43ddbaaee59712c7029005e1b6fae907ba75d7653e39bd73a97e4742a95f86f275b76277a7b45ae7b1a9c980777cde834a19082559ed1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
